### ISSUE TITLE
iron-selector doesn't select in nested templates

### ISSUE THREAD

**Issue by fooloomanzii** [PolymerElements/iron-selector#47] opened 2015-07-17 07:33 UTC
as an example:

![image](https://cloud.githubusercontent.com/assets/9318952/8742550/d5ac68e6-2c66-11e5-9f9e-86b42e7c3e23.png)

but it doesn't select and I can't figure out why

Code: http://jsbin.com/zuqato/edit?html,console,output

**Comment by fooloomanzii** [comment] 2015-07-17 07:41
it would look like this
![image](https://cloud.githubusercontent.com/assets/9318952/8742667/ff591e36-2c67-11e5-807e-ba3db6c64c87.png)
and nothing happens

if i select in the upper template like
![image](https://cloud.githubusercontent.com/assets/9318952/8742654/e17bc648-2c67-11e5-81f2-03981f4f611c.png)

it works:
![image](https://cloud.githubusercontent.com/assets/9318952/8742641/bd9d2604-2c67-11e5-9977-a28f549aa6b6.png)

**Comment by Trakkasure** [comment] 2015-07-25 03:38
In iron-selectable the get items() function queries only the distributed nodes. This would normally take care of it. However, templates embedded within another templates hide it's distributed nodes within the surrounding template. I understand using getDistributedNodes when no selectable attribute is specified. But why not just use querySelectorAll when a selectable attribute is specified?

**Comment by Trakkasure** [comment] 2015-07-25 04:04
@fooloomanzii Updated with my fix here: http://jsbin.com/pimazupare/edit?html,console,output

**Comment by fooloomanzii** [comment] 2015-07-25 10:29
Looks great! Thanks

**Comment by Trakkasure** [comment] 2015-07-27 21:43
Firefox seems to have a problem with the solution on only one test. What is weird, is I can make the test succeed by setting the selected item in the test itself. (as long as the item is different than the default selected item) This test succeeds in Chrome. I cannot test Safari, the driver won't work.

**Comment by notwaldorf** [comment] 2016-01-27 23:54
Closing as a duplicate of https://github.com/PolymerElements/iron-selector/issues/42. Currently iron-selector only looks at immediate children.

**Closed by notwaldorf** 2016-01-27 23:54 UTC

**Comment by yglodt** [comment] 2018-03-09 06:05
I have a somehow similar issue exposed with this code:

```
<iron-selector multi attr-for-selected="value" selected-values="{{selectedTimes}}">
	<template is="dom-repeat" items="[[days]]">
		<template is="dom-repeat" items="[[hours()]]" as="ind">
			<div value="[[itemval(item, ind)]]"></div>
		</template>
	</template>
</iron-selector>
```
Selection works well, the array _selectedTimes_ is changing as expected.

But pre-setting _selectedTimes_ does not mark any item as selected, strangely.
